experiment:
  name: "Heart Disease Prediction"
  run_name: "Model Testing v1"
  description: ""

cv:
  n_splits: 5
  n_candidates: 90
  factor: 2
  min_resources: "smallest"

feature:
  ignore: ["id", "FBS over 120", "BP", "Cholesterol"]
  numerical:
    [
      "Age",
      "BP",
      "Cholesterol",
      "Max HR",
      "ST depression",
      "Number of vessels fluro",
      "Slope of ST",
    ]
  categorical:
    [
      "Chest pain type",
      "FBS over 120",
      "EKG results",
      "Exercise angina",
      "Thallium",
      "Sex",
    ]

scaler:
  "standard": ["Age", "Max HR", "Number of vessels fluro", "Slope of ST"]
  "robust": ["BP", "Cholesterol", "ST depression"]

search_grid:
  - classifier: ["logistic_regression"]
    classifier__C: [1.3, 1.35, 1.4, 1.5]
    classifier__solver: ["lbfgs", "liblinear"]
    classifier__max_iter: [1000]
    classifier__class_weight: ["balanced"]
  - classifier: ["xgboost"]
    classifier__n_estimators: [800, 1000, 1200, 1400, 1500]
    classifier__learning_rate: [0.001, 0.01, 0.05, 0.1]
    classifier__max_depth: [3, 4, 5, 6]
    classifier__min_child_weight: [1, 5, 10]
    classifier__tree_method: ["hist"]
    classifier__random_state: [42]
    classifier__eval_metric: ["auc"]

scoring: "roc_auc"
