experiment:
  name: "Placeholder Experiment"
  description: "testing experiments"

cv:
  n_splits: 5

feature:
  ignore: []
  numerical:
    [
      "Age",
      "BP",
      "Cholesterol",
      "Max HR",
      "ST depression",
      "Number of vessels fluro",
      "Slope of ST",
    ]
  categorical:
    [
      "Sex",
      "Chest pain type",
      "FBS over 120",
      "EKG results",
      "Exercise angina",
      "Thallium",
    ]

scaler:
  "standard":
    [
      "Age",
      "BP",
      "Cholesterol",
      "Max HR",
      "ST depression",
      "Number of vessels fluro",
      "Slope of ST",
    ]

search_grid:
  - classifier: ["logistic_regression"]
    classifier__C: [0.01, 0.1, 1.0]
    classifier__solver: ["lbfgs", "liblinear"]
    classifier__max_iter: [1000]
    classifier__class_weight: ["balanced"]
  - classifier: ["xgboost"]
    classifier__n_estimators: [500]
    classifier__learning_rate: [0.01, 0.1]
    classifier__max_depth: [6, 8]
    classifier__tree_method: ["hist"]
    classifier__random_state: [42]

scoring: ["f1", "recall", "roc_auc"]
