experiment:
  name: "Heart Disease Prediction"
  run_name: "XGBoost Only v1"
  description: ""

cv:
  n_splits: 5
  n_candidates: 120
  factor: 2
  min_resources: "smallest"

feature:
  ignore: ["id"]
  numerical:
    [
      "Age",
      "BP",
      "Cholesterol",
      "Max HR",
      "ST depression",
      "Number of vessels fluro",
      "Slope of ST",
    ]
  categorical:
    [
      "Chest pain type",
      "FBS over 120",
      "EKG results",
      "Exercise angina",
      "Thallium",
      "Sex",
    ]

scaler:
  "standard": ["Age", "Max HR", "Number of vessels fluro", "Slope of ST"]
  "robust": ["BP", "Cholesterol", "ST depression"]

search_grid:
  - classifier: ["xgboost"]
    classifier__n_estimators: [200, 300, 400, 500, 1000, 1500, 2000]
    classifier__learning_rate: [0.005, 0.006, 0.0075, 0.009, 0.01, 0.0125]
    classifier__max_depth: [3, 4, 5, 6]
    classifier__subsample: [0.8]
    classifier__colsample_bytree: [0.8]
    classifier__tree_method: ["hist"]
    classifier__random_state: [42]
    classifier__eval_metric: ["auc"]
    classifier__gamma: [0.1, 0.2]

scoring: "roc_auc"
